triforce:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
        install: true
pipenv:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
    pipenv:
        symlink: ['pipenv', 'pew']
# epyqlib:
#     triforce:
#         venv_prefix: /home/altendky/venvs
#         symlink_prefix: /home/altendky/venvs/bin
#     st:
#         url: git+https://github.com/altendky/st@master
#     epyqlib:
#         url: git+https://github.com/altendky/st@lib
#         symlink: ['collectdevices']
twine:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
    twine:
        symlink: ['twine']
blurb:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
    blurb:
        symlink: ['blurb']
tox:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
    tox:
        symlink: ['tox']
flake8:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
    flake8:
        symlink: ['flake8']
git-cola:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
    git-cola:
        url: git+https://github.com/git-cola/git-cola@v3.0
        symlink: ['git-cola', 'git-dag']
    pyqt5:
        symlink: []
versioneer:
    triforce:
        venv_prefix: /home/altendky/venvs
        symlink_prefix: /home/altendky/venvs/bin
    versioneer:
        symlink: ['versioneer']
