# [virtualenv.venvs]
# install = [
#     "venvs",
# ]
# link = ["venvs"]

[virtualenv.virtualenv]
install = [
    "virtualenv",
]
link = ["virtualenv"]

[virtualenv.tox]
install = [
    "tox",
]
link = ["tox"]

# [virtualenv.pipenv]
# install = [
#     "git+https://github.com/pypa/pipenv",
# ]
# link = ["pipenv", "pew"]

[virtualenv.twine]
install = [
    "twine",
]
link = ["twine"]

[virtualenv.blurb]
install = [
    "blurb",
]
link = ["blurb"]

[virtualenv.flake8]
install = [
    "flake8",
]
link = ["flake8"]

# [virtualenv.git-cola]
# install = [
    # "https://github.com/git-cola/git-cola/archive/v3.6.tar.gz",
# ]
# link = ["git-cola", "git-dag"]

[virtualenv.versioneer]
install = [
    "versioneer",
]
link = ["versioneer"]

# [virtualenv.cython]
# install = [
#     "cython",
# ]
# link = ["cython"]

[virtualenv.ccstudiodss]
install = [
    "ccstudiodss",
]
link = ["dss"]

# [virtualenv.offlineimap]
# python = "python2"
# install = [
#     "six",
#     "offlineimap",
# ]
# link = ["offlineimap"]

[virtualenv.poetry]
python = "python3"
install = [
    "poetry",
]
link = ["poetry"]

# [virtualenv.pipx]
# python = "python3"
# install = [
#     "pipx",
# ]
# link = ["pipx"]

# [virtualenv.py2]
# python = "python2"

# [virtualenv.py3]
# python = "python3"

[virtualenv.black]
python = "python3"
install = [
    "black",
]
link = ["black"]

