[settings]
trusted_config_paths = ["~/repos/.mise.local.toml", "~/repos/gw"]

[shell_alias]
bs = "Bambu_Studio.AppImage"

[tool_alias]
bambustudio = "github:bambulab/BambuStudio"
grip = "pipx:grip"

# for gw
dockerfmt = "github:reteps/dockerfmt"
cargo-nextest = "github:nextest-rs/nextest"
cargo-audit = "cargo:cargo-audit"
cargo-llvm-cov = "aqua:taiki-e/cargo-llvm-cov"
cargo-modules = "cargo:cargo-modules"

[tools]
bun = "latest"
"github:bambulab/BambuStudio" = "latest"
"pipx:grip" = "latest"

# for gw
opentofu = "latest"
rust = { version = "stable", components = "llvm-tools" }
uv = "latest"
shfmt = "3.8.0"
shellcheck = "0.11.0"
actionlint = "1.7.9"
hadolint = "2.12.0"
"github:reteps/dockerfmt" = "0.3.9"
trivy = "latest"
"github:nextest-rs/nextest" = { version = "0.9.72", version_prefix = "cargo-nextest-" }
"cargo:cargo-audit" = "latest"
"aqua:taiki-e/cargo-llvm-cov" = "0.6.14"
"cargo:cargo-modules" = "latest"
"pipx:playwright" = "latest"
node = "latest"
npm = "latest"
gh = "latest"
claude-code = "latest"
"pipx:pre-commit" = "latest"
