[settings]
trusted_config_paths = ["~/repos/.mise.local.toml", "~/repos/gw"]

[shell_alias]
bs = "Bambu_Studio.AppImage"

[tool_alias]
bambustudio = "github:bambulab/BambuStudio"
grip = "pipx:grip"

[tools]
bun = "latest"
"github:bambulab/BambuStudio" = "latest"
opencode = "latest"
"pipx:grip" = "latest"
