[settings]
lockfile = true
locked = true
status = { missing_tools = "always" }
trusted_config_paths = ["~/repos/.mise.local.toml", "~/repos/gw"]

[shell_alias]
#bs = "Bambu_Studio.AppImage"

[tool_alias]
bs = "github:bambulab/BambuStudio"
grip = "pipx:grip"
orchestrator = "cargo:opencode-orchestrator-mcp"

# for gw
dockerfmt = "github:reteps/dockerfmt"
cargo-nextest = "github:nextest-rs/nextest"
cargo-audit = "cargo:cargo-audit"
cargo-llvm-cov = "aqua:taiki-e/cargo-llvm-cov"
cargo-modules = "cargo:cargo-modules"

[env]
OPENCODE_BINARY = { value = "{{ tools.opencode.path }}/opencode", tools = true }

[tools]
bun = "latest"
bs = { version = "latest", prerelease = true, bin = "bs", asset_pattern = "*ubuntu*24.04*.AppImage" }
"github:rustdesk/rustdesk" = { version = "latest", bin = "rustdesk", asset_pattern = "*x86_64.AppImage" }
"pipx:grip" = "latest"

# for gw
opentofu = "latest"
# rust = { version = "stable", components = "llvm-tools" }
uv = "latest"
shfmt = "3.8.0"
shellcheck = "0.11.0"
actionlint = "1.7.9"
hadolint = "2.12.0"
"github:reteps/dockerfmt" = "0.3.9"
trivy = "latest"
"github:nextest-rs/nextest" = { version = "0.9.72", version_prefix = "cargo-nextest-" }
cargo-binstall = "latest"
"cargo:cargo-audit" = "latest"
"aqua:taiki-e/cargo-llvm-cov" = "0.6.14"
"cargo:cargo-modules" = "latest"
"npm:playwright" = "latest"
node = "latest"
npm = "latest"
gh = "latest"
"conda:git" = "latest"
claude-code = "latest"
opencode = "1.17.4"
"pipx:pre-commit" = "latest"
"pipx:mergify-cli" = "latest"
just = "latest"
mold = "latest"
"cargo:opencode-orchestrator-mcp" = "0.7.9"

bitwarden = "latest"
mitmproxy = "latest"
"cargo:rust-script" = "latest"
zig = "latest"
"npm:node-gyp" = "latest"
"npm:@openai/codex" = "latest"
ripgrep = "latest"
cmake = "latest"
ninja = "latest"
aws = { version = "latest", symlink_bins = "true" }
python = "latest"
markdownlint-cli2 = "latest"
